## Andrej Aderhold
## date: 6.10.2016


* Tasks

** TODO Check warnings for decision trees. The cost matrix needs names. Just add some:

"In C5.0.default(x = treetraining, y = as.factor(data.sc[-i,  ... : 
no dimnames were given for the cost matrix; the factor levels will be used"

** TODO gp_ard_lscales_prob() : scale of x and y coordinates is not in original format. Might change this.

** DONE Decision-Trees: combine MSE plots for different boosting trials (1 and 10). 
** DONE Data heart_data has ED = 10 value, although it should be around 140. Check Excel tables!** 
** DONE Put script evaluate_decision_tree.R call into run_MI_classifiers.R ?
** DONE Univariate code uses simple logistic regression with single feature. Try something else or OK?
** DONE Modify output of roc_points_results.csv to tab separated and without leading column.
** DONE GP-ARD : include scripts gpard_lscales_prob.m and gpard_probmesh.m into gp_ard.m main script.
** DONE GP-ARD : in gp_ard.m:185 -> sample Binomial using probabilities instead of decision criteria.


* Issues

** Warning : GP-ARD (gp_ard.m) [OBSERVE] Only do something when the data set is really expanded. 

"Warning: Inference method failed [Error using chol
Matrix must be positive definite with real diagonal.] .. attempting to continue 
> In gp (line 128)
  In minimize (line 97)
  In gp_ard>gp_core (line 182)
  In gp_ard (line 37) "

There will be no valid result. Happens whenever I have the  "Age" variable together with the "Ta/SBP" variable in the design matrix.
E.g. heart_data = all_data(:,[id_type, id_ta, id_treq, id_sbp, id_edv, id_tatreq, id_tasbp, id_age]);

Maybe an adjustment of the inital length parameter fixes this? It helped with previous problem I had with gpml.


** Warning : Lasso (glmnet) [IGNORE]

"In lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  :
  one multinomial or binomial class has fewer than 8  observations; dangerous ground"

This warnings is generated by executing glmnet. The problem is that there are less than 8 class '1' observations.
As long as the data does not provide more observation, the message should be ignored.



** Error : quickhull_roc.R [FIXME]

"Fehler in if (hull_x[1] >= x[i]) next (von quickhull_roc.R#109) : 
  Fehlender Wert, wo TRUE/FALSE nötig ist"

Happens when only one point is in the ROC curve. For some reason the quickhull calculation fails.



** Warning : GLM [IGNORE]

"glm.fit: fitted probabilities numerically 0 or 1 occurred
34: glm.fit: algorithm did not converge"

Happens alot of times while executing LOOCV. Ignore so far.
